### ISSUE TITLE
CSV Export for Upload to Remote Website`

### ISSUE THREAD

**Issue by ayush0624** [glasswindow/FRC-Advanced-Scouting-Touchstone#2]
Where is the CSV export file located containing all of the scouting data, and is it possible to upload that file to a remote website? If not, what would be the best way to transfer the scouting data from the application to a custom web app.

**Comment by aaronkampmeier** [comment]
The CSV Export feature simply exports all of the compiled stats about a team (basically everything you would see in the team's page in the app). That file you can use however you like and can upload it to your custom system if you want. All of the data about what happened in individual matches, team comments, team images, the order of the pick list, and picked teams is stored in backend databases on AWS and should not be considered directly exportable. However if you would like to develop your own web frontend that pulls from (or pushes to) a team's FAST data, I would love to work with you on the api for accessing the AWS backend.
